### ISSUE TITLE
Undefined var?

### ISSUE THREAD

**Issue by ldidry** [Arvedui/tt-rss-tumblr-gdpr#1]
In https://github.com/Arvedui/tt-rss-tumblr-gdpr/blob/7d0db3d86aa9cedfd194ce189a22d471e5f81e1c/tumblr_gdpr/init.php#L53, you have a var `$url`, coming from nowhere. Did you mean `$fetch_url`?

I didn't test the plugin, I only have read the code.

**Comment by Arvedui** [comment]
Yes … 
Thank you!
